### ISSUE TITLE
Update to work with TWW please

### ISSUE THREAD

**Issue by Daveo7** [Torhal/Frenemy#5]
Is it possible to get this updated to work with 11.0.2 please

**Comment by Manta7388** [comment]
You can change following File:
[Install Path]\Interface\AddOns\Frenemy\Preferences\_Main.lua

From "GetAddonMetaData" to "C_AddOns.GetAddonMetaData" (Line 10)

This should solve the issue

**Comment by Daveo7** [comment]
Done this but still don't get the dropdown box (lists who in guild/friends lists are online) when I hover over the LDB information.

Dropdown (tooltip) sample...
![pvw62599](https://github.com/user-attachments/assets/3a7697a4-214f-43fa-afe6-dc949e502ae5)

Also, the actual file you were referring to is [Install Path]\Interface\AddOns\Frenemy\Preferences/_Main.lua (around line 12).

This...
local metaVersion = GetAddonMetaData(AddOnFolderName, "Version")

to this...
local metaVersion = C_AddOns.GetAddonMetaData(AddOnFolderName, "Version")

**Comment by Daveo7** [comment]
Can't get tooltip (as per above image) to display.

I get this error if I hover over the Frenemy LDB...

Message: Interface/AddOns/Frenemy/TooltipHandler/Render.lua:138: attempt to call method 'Acquire' (a nil value)
Time: Mon Aug 19 22:01:16 2024
Count: 2
Stack: Interface/AddOns/Frenemy/TooltipHandler/Render.lua:138: attempt to call method 'Acquire' (a nil value)
[string "=[C]"]: in function `Acquire'
[string "@Interface/AddOns/Frenemy/TooltipHandler/Render.lua"]:138: in function `Render'
[string "@Interface/AddOns/Frenemy/DataObject.lua"]:47: in function `OnEnter'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:219: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:93: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:83>

**Comment by Michaa1000** [comment]
the correct line is:

local metaVersion = C_AddOns.GetAddOnMetadata(AddOnFolderName, "Version")

**Comment by Daveo7** [comment]
Thanks for that, but it doesn't fix the LDB tooltip display when you hover over the Frenemy information.

**Comment by Michaa1000** [comment]
i'm not a coder, i just found 2 spelling-errors in the original fix.

atm i get this tooltip. get errors only by clicking on entries of guildmembers.
![Frenemy_screenshot2](https://github.com/user-attachments/assets/0800d5ec-9a69-4490-b4e3-b844dd6b0614)

my _Main.lua

[_Main.zip](https://github.com/user-attachments/files/16882403/_Main.zip)

**Comment by Daveo7** [comment]
Even with your _Main.lua, I get no tooltip and still getting the following error when I hover over the Frenemy LDB...

Message: Interface/AddOns/Frenemy/TooltipHandler/Render.lua:138: attempt to call method 'Acquire' (a nil value)

Looks like something in the TooltipHandler's Render.lua file is causing the tooltip to not display.

UPDATE
======
Found the issue, I was using an updated version of Frenemy from WoWInterface (v10.1.0.1), where they had updated Lib-Qtip-1.0 to Lib-Qtip-2.0, and I think this is what was cuasing the non-display of tooltip issue.

I uninstalled the updated version, reinstalled v10.0.7.3, update the local metaVersion line in Preferences/_Main.lua, then logged into the game, and I can now see the tooltip again :)

Not worried about the errors on clicking guild members, as I mainly use the tooltip just to see who's online.

Many thanks for the help tho :)
